version: '3'
services:
  console:
    build: .
    image: helium/console:latest
    container_name: helium_console
    restart: always
    env_file: .env
    ports:
      - 4000:4000
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: helium_postgres
    restart: always
    environment:
        - POSTGRES_DB=console
        - POSTGRES_PASSWORD=postgres
    volumes:
      - "./data/postgres/:/var/lib/postgresql/data"
  router:
    image: helium/router:latest
    container_name: helium_router
    restart: always
    env_file: .env-router
    ports:
      - 2154:2154
    volumes:
      - "./data/router:/var/data"
    depends_on:
      - console