import React, { Component } from 'react';
import { Typography } from 'antd';
const { Text } = Typography
import DocumentLayout from '../common/DocumentLayout'

const styles = {
  terms: {
    flex: 1,
    padding: 20,
  },
}

class VIPTerms extends Component {
  render() {
    return(
      <DocumentLayout>
        <div style={styles.terms}>
        <Text>
        <p><i><b>Last Revised on July 10, 2023</b></i></p>
        <h3>NOVA LABS, INC. TERMS AND CONDITIONS</h3>

        <p>
          These Terms and Conditions (“<b>Terms</b>”) form a legal agreement between you (either an individual or a single entity) (“<b>You</b>” or “<b>Customer</b>”) and Nova Labs, Inc. (“<b>Nova</b>”). The term of these Terms will become effective on the date you agree and accept these Terms. The website and any contents, tools, features and functionality offered on or through our platform are collectively referred as to (“<b>Services</b>”).
        </p>

        <p><b>
          THESE TERMS GOVERN YOUR ACCESS TO AND USE OF THE PLATFORM WHICH INCLUDES WITHOUT LIMITATION YOUR USE OF THE OTHER SOFTWARE AND SERVICES PROVIDED IN CONNECTION WITH THE PLATFORM. PLEASE READ THESE TERMS CAREFULLY, AS THEY INCLUDE IMPORTANT INFORMATION  ABOUT YOUR LEGAL RIGHTS AND OBLIGATIONS. BY CLICKING ON “I AGREE,” ACCESSING, OR USING THE PLATFORM IN ANY MANNER, YOU ACCEPT AND AGREE TO BE BOUND BY THESE TERMS. YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, POWER, AND AUTHORITY TO ENTER INTO THESE TERMS ON BEHALF OF CUSTOMER AND BIND CUSTOMER TO ITS TERMS. IF CUSTOMER DOES NOT AGREE TO THE TERMS, YOU MUST NOT ACCESS OR OTHERWISE USE THE PLATFORM. FROM TIME TO TIME WE MAY UPDATE THIS PLATFORM AND THESE TERMS.  YOUR USE OF THIS PLATFORM AFTER WE POST ANY CHANGES TO THESE TERMS CONSTITUTES CUSTOMER’S AGREEMENT TO THOSE REVISED TERMS.
        </b></p>

        <h5><b><u>Definitions.</u></b></h5>
        <ul>
        <li><b>"Authorized Users"</b> means Customer’s employees and contractors who are authorized by Customer to use the Platform.</li>
        <li><b>"Platform"</b> means any Nova website, portal, and/or online service provided by Nova in which Nova makes available the Nova Content. The Platform includes the Nova Content. </li>
        <li><b>"Nova Content"</b> means the information, data, reports, content and materials provided by Nova through the Platform. Nova Content includes: (a) information, data, reports, content and materials created or developed by or on behalf of Nova; and (b) information, data, content and materials licensed or obtained by Nova from a third party.</li>
        <li><b>“Sensitive Information”</b> means credit or debit card numbers; financial account numbers or wire instructions; government issued identification numbers (such as driver’s licenses, Social Security numbers, passport numbers), biometric information; personal health information (or other information protected under any applicable health data protection laws); personal information of children protected under any child data protection laws; export-controlled information for which Customer has not obtained all required export licenses or government approvals; racial or ethnic origin; and/or security or access codes or passwords.</li>
        <li><b>“Third-Party Materials”</b> means third-party data, information, applications, websites, and other products, services, and/or materials not maintained or related to Nova or the Platform.</li>
        </ul>

        <h5><b><u>The Platform.</u></b></h5>
        <ul>
        <li><i><b>License Grant.</b></i> Nova grants Customer a revocable, limited, non-exclusive, non-transferable, non-sublicensable right to have its Authorized Users: (a) access the features and functions of the Platform solely for Customer’s internal business purposes; and (b) view, download, and use the Nova Content made available to Customer through the Platform solely for such Authorized User’s individual use for Customer’s internal business purposes.</li>
        <li><i><b>Ownership.</b></i> Customer acknowledges that the Platform is provided under license, and not sold, to Customer. Customer does not acquire any ownership interest in the Platform under these Terms, or any other rights to the Platform other than to use the Platform in accordance with the Terms, subject to all terms, conditions, and restrictions. Nova reserves and shall retain its entire right, title, and interest in and to the Platform and all intellectual property rights arising out of or relating to the Platform and all improvements, enhancements, modifications, and updates thereto. Customer shall safeguard the Platform (including all copies thereof) from infringement, misappropriation, theft, misuse, or unauthorized access. </li>
        <li><i><b>Feedback.</b></i> Customer may submit suggestions, comments or other feedback (collectively, “<b>Feedback</b>”) to Nova with respect to the Platform. Customer hereby grants Nova a world-wide, non-exclusive, perpetual and irrevocable license ( for as long as your content is stored with us) to use and exploit such Feedback in order to improve or operate the  Services including incorporating such Feedback within its products and services, without providing payment or any other consideration to Customer. Nova has no confidentiality or other obligations with respect to Customer’s Feedback.</li>
        <li><i><b>Third-Party Materials.</b></i> The Platform may display, include, or make available Third-Party Materials. Customer acknowledges and agrees that Nova is not responsible and makes no representations, endorsements, or warranties, express or implied, for Third-Party Materials, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. Company does not assume and will not have any liability or responsibility to you or any other person or entity for any Third-Party Materials. Third-Party Materials and links thereto are provided solely as a convenience to you, and your access and use of them is entirely at your own risk and subject to such third parties' terms and conditions. Information you submit to a Third-Party Material accessible from this Platform is subject to the terms of that site's terms of use and privacy policy. Nova has no control over how your information is collected, used, or otherwise handled.</li>
        </ul>

        <h5><b><u>Customer Restrictions.</u></b></h5>
        <ul>
        <li><i><b>Limitations on Copying and Distribution.</b></i> Customer may not copy or distribute the Platform except to the extent that copying is necessary to use the Platform for purposes set forth herein. </li>
      	<li><i><b>Limitations on Reverse Engineering and Modification.</b></i> Customer may not reverse engineer, decompile, disassemble, decode (including any underlying idea or algorithm), modify or create works derivative of the Platform, or use Nova’s intellectual property or any Nova Content to develop a service similar to the Platform. </li>
      	<li><i><b>Sublicense, Rental and Third Party Use.</b></i> Customer may not assign, sublicense, rent, timeshare, loan, lease or otherwise transfer the Platform, or directly or indirectly permit any third party to use or copy the Platform. </li>
      	<li><i><b>Proprietary Notices.</b></i> Customer may not use, reproduce, remove or destroy any copyright, trademark, service mark, trade name, slogan, logo, image or other proprietary notation displayed on the Platform. </li>
      	<li><i><b>Unauthorized Access.</b></i> Customer may not attempt to gain unauthorized access to, interfere with, damage or disrupt the Platform, accounts registered to other customers, or the computer systems or networks connected to the Platform.</li>
      	<li><i><b>Unethical Use.</b></i> Customer may not use the Platform for illegal, harassing, unethical or disruptive purposes.     </li>
      	<li><i><b>Use in Accordance with Documentation.</b></i> All use of the Platform shall be in accordance with any then-current documentation.</li>
      	<li><i><b>Use of Platform not Transferable.</b></i> The right to use the Platform is personal to each Authorized User and is not transferable by such user by assignment, sublicense, or any other method to any other person or entity. Any attempt by an Authorized User to transfer such user's rights shall be void and shall constitute a breach of these Terms.</li>
      	<li><i><b>No Sensitive Information.</b></i> Customer may not use the Platform to collect, manage, or process Sensitive Information. Nova specifically disclaims any liability that may result from Customer’s use of the Platform to collect, process, or manage Sensitive Information. </li>
      	<li><i><b>No Service Bureau.</b></i> Customer may not use the Platform in the context of a service bureau for the benefit of third parties.</li>
      	<li><i><b>Prohibited Uses.</b></i> Customer shall be prohibited from using the Platform for any purpose that is unlawful, tortious, abusive, intrusive on another's privacy, harassing, libelous, defamatory, embarrassing, obscene, threatening, or hateful.</li>
        </ul>

        <h5><b><u>Platform Access, Security and Restrictions.</u></b></h5>
        <p>The Platform may contain technological copy protection or other security features designed to prevent unauthorized use of the Platform, including features to protect against use of the Platform as prohibited under Section 3. Customer shall not attempt to, remove, disable, circumvent, or otherwise create or implement any workaround to, any such copy protection or security features. Without limiting the foregoing, Customer is prohibited from violating or attempting to violate the security of the Platform, including, without limitation: (a) accessing data not intended for such user or logging onto a server or an account which the user is not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) accessing or using the Platform or any portion thereof without authorization, in violation of these Terms or in violation of applicable law; or (d) store or transmit malicious code through the Platform. Customer may not use any scraper, crawler, spider, robot or other automated means of any kind to access or copy data on the Platform, deep-link to any feature or content on the Platform, bypass robot exclusion headers or other measures we may use to prevent or restrict access to the Platform. Nova may terminate and/or suspend Customer or any Authorized User’s access to any or all of the Platform without notice, for non-payment of Fees, or any use of the Platform in a way that violates applicable local, state, federal, or foreign laws or regulations, these Terms, or any applicable master customer agreement (the “<b>Agreement</b>”).</p>

        <h5><b><u>Collection and Use of Information.</u></b></h5>
        <ul>
        <li><i><b>Customer Obligations.</b></i> The Platform gives Customer the ability to track and monitor data, media, products, and other information Customer inputs into the Platform (excluding Sensitive Information). Customer may use the Platform to track and monitor data about its own customers (“<b>Customer End-Users</b>”). Customer maintains sole responsibility for determining what data is to be tracked and sent to the Platform. Customer also maintains all responsibility for determining whether the Platform or the information generated thereby is accurate or sufficient for Customer’s purposes. Customer agrees to comply with all applicable privacy, data protection, and consumer protection laws and regulations in connection with its use of the Platform, including, without limitation, requirements of proper notice and consent (including for any Customer End-Users) to process and send personal information to Nova as contemplated under these Terms.</li>
        <li><i><b>Customer Data.</b></i> Nova may, directly or indirectly through the services of others, collect and store information regarding use of the Platform and about equipment on which the Platform is installed or through which it otherwise is accessed and used, including, but not limited to, by means of security measures included in the Platform as described in Section 4. Customer grants Nova a non-exclusive, world-wide, perpetual, royalty-free license to use the data and other information collected, shared, or otherwise input by Customer into the Platform (collectively, “<b>Customer Data</b>”) for purposes of performing these Terms. Without limiting the foregoing, Nova may also use Customer Data for: (a) improving the performance of the Platform or developing updates; (b) verifying compliance with the Terms and enforcing Nova’s rights, including all intellectual property rights in and to the Platform; and (c) other internal business and product development purposes. Nova may also use and exploit Customer Data in an aggregate, de-identified and/or anonymized manner for any other Nova business purpose, provided it does not directly or indirectly identify Customer or any Customer End-User. </li>
        <li><i><b>Data Processing Addendum.</b></i> To the extent Customer uses the Platform to input, collect, or otherwise process personal information from Customer End-Users located in the European Economic Area or the United Kingdom, the terms of the Data Processing Addendum (“<b>DPA</b>”) shall apply and be deemed incorporated into this Agreement. Please also consult our Privacy Policy for a description of our privacy practices and policies. Our Privacy Policy is a part of these Terms and You agree to our use and sharing of the information we collect as described in our Privacy Policy. </li>
        </ul>

        <h5><b><u>Compliance with Law.</u></b></h5>
        <p>Customer shall be solely responsible for ensuring that Customer and each Authorized User’s use of the Platform is in compliance with all applicable foreign, federal, state and local laws, and rules and regulations.</p>

        <h5><b><u>Payment.</u></b></h5>
        <ul>
        <li><i><b>Fees.</b></i> Customer shall pay Nova the fees set forth in any applicable Order Form and/or Invoice (“<b>Fees</b>”) in accordance with these Terms and the Invoice. If not otherwise specified on an Order Form and/or invoice, Fees will be due upon receipt of an invoice. Except as otherwise specifically provided in these Terms, all Fees paid and payable to Nova hereunder are non-cancelable and non-refundable. If Customer fails to pay any amounts due under these Terms by the due date, in addition to any other rights or remedies it may have under this Agreement or by matter of law: (a) Nova reserves the right to suspend the Services immediately, until such amounts are paid in full; and (b) Nova reserves the right to charge interest at a rate equal to 5% percent per month or the maximum rate permitted by applicable law until Customer pays all amounts due. Nova will not exercise its right to charge interest if the applicable charges are under reasonable and good faith dispute and Customer is cooperating diligently to resolve the issue. </li>
        <li><i><b>Taxes.</b></i> Fees do not include any local, state, federal or foreign taxes, levies, duties or similar governmental assessments of any nature, including value-added, use or withholding taxes (collectively, “<b>Taxes</b>”). Customer is responsible for paying all Taxes associated with its purchases hereunder (excluding taxes based on Nova’s net income or property) unless Customer provides Nova with a valid tax exemption certificate authorized by the appropriate taxing authority. </li>
        </ul>

        <h5><b><u>Indemnification.</u></b></h5>
        <p>Customer shall indemnify, defend, and hold harmless Nova and its respective representatives, successors, directors, officers, agents, and permitted assigns from and against any and all claims, action, liability, damages, or expense, including, without limitation, attorneys’ fees, arising out of or related to: (a) the gross negligence or willful misconduct of Customer or its representatives in the performance of Customer’s obligations under these Terms; (b) Customer’s violations of applicable laws or infringement of intellectual property rights; (c) Customer’s breach of any representations and warranties; and/or (d) Customer’s breach of Section 3 and/or Section 5. </p>

        <h5><b><u>Limitation of Liability.</u></b></h5>
        <p>NOVA IS NOT RESPONSIBLE NOR LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION) ARISING OUT OF OR RELATING IN ANY WAY TO THE PLATFORM, PLATFORM-RELATED SERVICES, NOVA CONTENT OR INFORMATION CONTAINED WITHIN THE PLATFORM, AND/OR ANY LINKED WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. CUSTOMER’S SOLE REMEDY FOR DISSATISFACTION WITH THE PLATFORM, PLATFORM-RELATED SERVICES, NOVA CONTENT, AND/OR LINKED WEBSITES IS TO STOP USING THE PLATFORM AND/OR THOSE SERVICES.</p>

        <h5><b><u>Warranties; Disclaimer of Warranties.</u></b></h5>
        <ul>
        <li><i><b>Mutual Warranties.</b></i> Each Party hereby represents and warrants (a) that it is duly organized, validly existing and in good standing under the laws of its jurisdiction of incorporation or organization; (b) that it has the legal power and authority to enter into these Terms; and (c) that these Terms, when executed and delivered, will constitute a valid and binding obligation of such Party and will be enforceable against such Party in accordance with its terms.</li>
        <li><i><b>Customer Warranties.</b></i> Customer represents and warrants that it owns or has obtained all necessary rights, title and interest, provided all appropriate notices and disclosures, and obtained all necessary permissions and consents, to use the Platform to track end products and submit Customer Data to the Platform for purposes of Nova processing in accordance with this Agreement.</li>
        <li><i><b>Disclaimer of Warranty.</b></i> <b>THIS PLATFORM, INCLUDING ANY NOVA CONTENT OR INFORMATION CONTAINED WITHIN IT OR ANY PLATFORM-RELATED SERVICE, IS PROVIDED "AS IS," WITH ALL FAULTS, WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUALITY OF INFORMATION, QUIET ENJOYMENT, AND TITLE/NON-INFRINGEMENT. NOVA DOES NOT WARRANT THE ACCURACY, COMPLETENESS OR TIMELINESS OF THE INFORMATION OBTAINED THROUGH THE PLATFORM.</b></li>
        </ul>

        <h5><b><u>Miscellaneous Provisions.</u></b></h5>
        <ul>
        <li><i><b>Export Regulation.</b></i> The Platform may be subject to US export control laws, including the U.S. Export Administration Act and its associated regulations. Customer shall not, directly or indirectly, export, re-export, or release the Platform to, or make the Platform accessible from, any jurisdiction or country to which export, re-export, or release is prohibited by law, rule, or regulation. Customer shall comply with all applicable federal laws, regulations, and rules, including, without limitation the U.S Export Administration Regulations and U.S sanctions regulations, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Platform available outside the U.S. This includes the prohibition against transactions with: (i) a national or resident of any country subject to U.S. sanctions or similar restrictions (currently, Cuba, Iran, Syria, North Korea, and the region of Crimea), or (ii) anyone on the U.S Treasury Department's list of Specially Designated Nationals or other sanctions list.     </li>
        <li><i><b>Force Majeure.</b></i> Nova will not be liable for any failure or delay in performance under these Terms which is due to any event beyond its reasonable control, including without limitation, fire, explosion, pandemic, unavailability of utilities or raw materials, unavailability of components, war, riot, act of God, export control regulation, laws, judgements or government instructions.</li>
        <li><i><b>Entire Agreement; Modifications.</b></i> We may modify these Terms from time to time in which case we will update “Last Revised” date at the top of these Terms. If we make changes that are material, we will use reasonable efforts to attempt to notify Customer such as by e-mail and/or by placing prominent notice on the first page of the website and/or by implementing a mandatory click-through process. In the event we implement a mandatory click-through process for any material change to these Terms, Customer agrees and acknowledges they have read the changes and acceptance of the modified Terns will become effective. However, it is Customer’s sole responsibility to review these Terms from time to time to view any such changes. Customer continued access and/or use of the Platform after modification has become effective will be deemed acceptance of modified Terms. These Terms constitutes the entire understanding between the parties related to these Terms, which understanding supersedes and merges all prior understandings and all other proposals, letters, agreements, oral or written. Nothing in these Terms, express or implied, is intended to or will confer upon any third-party person or entity any right, benefit or remedy of any nature whatsoever under or by reason of these Terms.</li>
        <li><i><b>Assignment.</b></i> Customer may not assign its rights or delegate its duties under these Terms either in whole or in part without the prior written consent of Nova. Any attempted assignment or delegation without such consent will be void and Nova may immediately terminate these Terms for cause. Nova may assign these Terms without Customer’s consent to any affiliate or in the event of a merger, acquisition, or sale of all or substantially all of its assets. Except as provided above, these Terms shall apply to, inure to the benefit of, and be binding upon the parties hereto and their successors and assigns. </li>
        <li><i><b>Governing Law; Severability.</b></i> These Terms are governed by and construed in accordance with the internal laws of the State of California without giving effect to any choice or conflict of law provision or rule (whether of the State of California or any other jurisdiction) that would cause the application of Laws of any jurisdiction other than those of the State of California. You hereby agree that any and all disputes regarding these Terms will be subject to the courts located in San Francisco, California.  In the event any provision of these Terms is held by a tribunal of competent jurisdiction to be contrary to law, the remaining provisions of these Terms will remain in full force and effect.</li>
        <li><i><b>Publicity.</b></i> Nova may use Customer’s name, logo, and any non-confidential materials produced hereunder in Nova’s portfolio, on Nova’s website, intranet, and for internal and trade purposes. Nova will be required to obtain Client's advance approval to utilize Customer’s other trademarks and any other Customer materials or information in press releases, Nova brochures, or award submissions.</li>
        <li><i><b>Contact.</b></i>  You may contact us regarding the Platform or these Terms by email at support@nova-labs.com.</li>
        </ul>

        </Text>
        </div>
      </DocumentLayout>
    )
  }
}

export default VIPTerms
