version: '3'
services:
  console:
    build:
      context: .
      args:
        socket_check_origin: "${SOCKET_CHECK_ORIGIN}"
    image: helium/console:latest
    container_name: helium_console
    restart: always
    env_file: .env
    ports:
      - 4000:4000
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: helium_postgres
    restart: always
    volumes:
      - "./data/postgres/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=console
      - POSTGRES_PASSWORD=postgres
  router:
    image: quay.io/team-helium/router:latest
    container_name: helium_router
    restart: always
    env_file: .env-router
    # Double check your DNS by running the following command and looking for "DNS Servers"
    # > systemd-resolve --status
    dns: 172.31.0.2
    ports:
      - 2154:2154
      - 8080:8080 # gateway grpc
    volumes:
      - "./data/router:/var/data"
    depends_on:
      - console
  nginx:
    image: nginx:latest
    container_name: helium_nginx
    restart: always
    volumes:
      - "./data/nginx:/var/log/nginx"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - console
